#include <iostream>
#include <string>

using namespace std;

//This function displays the colors that the user inputed
void display(string guess) {
	cout << "\nYour guess: \n";
	for (int i = 0; i < guess.length(); i++) {
		char color = guess[i];
		switch(toupper(color)) 
		{
			case 'R': cout << ansi::foreground::RED << "\u2B24 ";
					break;

			case 'W': cout << ansi::foreground::WHITE << "\u2B24 ";
					break;

			case 'O': cout << ansi::foreground::ORANGE << "\u2B24 ";
					break;

			case 'G': cout << ansi::foreground::GREEN << "\u2B24 ";
					break;

			case 'B': cout << ansi::foreground::BLUE << "\u2B24 ";
					break;

			case 'P': cout << ansi::foreground::PURPLE << "\u2B24 ";
					break;
		}
	}
	cout<< ansi::RESET << endl << endl;
}
//This function will display the answer that is generated by the computer
void displaySol(char sol[]) {
	cout << "The correct answer is: \n";
	char color;
	for (int i = 0; i < 4; i++) {
		color = sol[i];
		switch(toupper(color)) 
		{
			case 'R': cout << ansi::foreground::RED << "\u2B24 ";
					break;

			case 'W': cout << ansi::foreground::WHITE << "\u2B24 ";
					break;

			case 'O': cout << ansi::foreground::ORANGE << "\u2B24 ";
					break;

			case 'G': cout << ansi::foreground::GREEN << "\u2B24 ";
					break;

			case 'B': cout << ansi::foreground::BLUE << "\u2B24 ";
					break;

			case 'P': cout << ansi::foreground::PURPLE << "\u2B24 ";
					break;
		}
	}
	cout<< ansi::RESET << endl << endl;
}